### ISSUE TITLE
Rechazar login si la alarma esta inactiva

### ISSUE THREAD

**Issue by edvm** [teritos/tero-ftpd#6]
Si la alarma del usuario esta inactiva, rechazar login. Otra opcion es implementar esto en tero-saas. Evaluar e implementar la solucion mas sencilla.

**Comment by jcarizza** [comment]
@edvm solucionado con https://github.com/teritos/tero-ftpd/blob/fdde57e98921c16dc2c3c46685eebf4ca4ad8f13/teroftpd/authorizer.py#L85
