### ISSUE TITLE
Autenticar usuario con el modelo FTPAccount de tero saas

### ISSUE THREAD

**Issue by jcarizza** [teritos/tero-ftpd#9]

**Comment by jcarizza** [comment]
Esto está encaminado con https://github.com/teritos/tero-ftpd/commit/f54a25b55f46b92de7962a9cae707fbd50cd0d84

Me falta hashear el password que se almacena en la base de datos y mergeamos. @edvm

**Comment by edvm** [comment]
Genial @jcarizza , pegue una googleada rapida a como hashear el password para que quede como Django lo storea, pero parece no ser tan simple jeje.

**Comment by jcarizza** [comment]
Sí eso parece más complicado. Usé una libreria recomendada bcrypt, que se encarga del salt y es más dificil de crackear.
